### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ctmayhew** [BorjaMerino/DoublePulsar-Volatility#1]
Hi I get the following error when trying to run the module, any pointers?

`ERROR   : volatility.debug    : The pdb file could not be downloaded. Try it with the PDB_FILE option.`

**Comment by BorjaMerino** [comment]
The plugin tries to download de symbol file from Microsoft to resolve SrvTransaction2DispatchTable. Did you run it with internet connection? You can download it on your own; for instance, with radare and provide it to the plugin with the PDB_FILE option. Take a look at:  http://www.shelliscoming.com/2017/08/doublepulsar-smb-implant-detection-from.html  
Let me know if the problem persists.

**Comment by ctmayhew** [comment]
Using the plugin without the pdb_file option fails, but using redare to download the PDB file worked! Thanks!

**Comment by BorjaMerino** [comment]
You are welcome! Thank you for reporting the issue, I will try to debug the problem.
